package com.app.miaaw.managers;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.app.miaaw.Domain.Admin;
import com.app.miaaw.repos.AdminRepository;

/**
 * Generated by Spring Data Generator on 23/04/2019
 */
@Component
@RestController
@RequestMapping("/admins")
public class AdminManager {

	private AdminRepository adminRepository;

	@Autowired
	public AdminManager(AdminRepository adminRepository) {
		this.adminRepository = adminRepository;
	}

	@GetMapping
	public ResponseEntity getAanbiedingen() {
		List<Admin> admins = adminRepository.findAll();
		if (admins == null) {
			return ResponseEntity.status(409).build();
		}

		return ResponseEntity.status(200).body(admins);
	}
}
