package com.app.miaaw.managers;

import com.app.miaaw.Domain.Admin;
import com.app.miaaw.Domain.CodeTemplate;
import com.app.miaaw.WebpageEnhancer.Enhancer;
import com.app.miaaw.repos.CodeTemplateRepository;
import com.app.miaaw.requests.EnhanceRequestLink;

import java.io.IOException;
import java.util.List;

import javax.servlet.http.HttpServletRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
* Generated by Spring Data Generator on 23/04/2019
*/
@Component
@RestController
@RequestMapping("/enhance")
public class CodeTemplateManager {

	private CodeTemplateRepository codeTemplateRepository;

	@Autowired
	public CodeTemplateManager(CodeTemplateRepository codeTemplateRepository) {
		this.codeTemplateRepository = codeTemplateRepository;
	}
	@PostMapping
	public ResponseEntity getEnhanced(@RequestBody EnhanceRequestLink request) throws IOException {
		String htmlCode = "";
		String link = request.getLink();
		//Moet nog de juiste codetemplate meegeven     \/\/\/\/\/
		htmlCode = Enhancer.enhanceDocument(link, new CodeTemplate()).toString();
		return ResponseEntity.status(200).body(htmlCode);
	}

}
