package com.app.miaaw.managers;

import com.app.miaaw.Domain.CodeTemplate;
import com.app.miaaw.repos.CodeTemplateRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/04/2019
*/
@Component
public class CodeTemplateManager {

	private CodeTemplateRepository codeTemplateRepository;

	@Autowired
	public CodeTemplateManager(CodeTemplateRepository codeTemplateRepository) {
		this.codeTemplateRepository = codeTemplateRepository;
	}

}
