package com.app.miaaw.managers;

import com.app.miaaw.Domain.FormOpties;
import com.app.miaaw.repos.FormOptiesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/04/2019
*/
@Component
public class FormOptiesManager {

	private FormOptiesRepository formOptiesRepository;

	@Autowired
	public FormOptiesManager(FormOptiesRepository formOptiesRepository) {
		this.formOptiesRepository = formOptiesRepository;
	}

}
