package com.app.miaaw.managers;

import com.app.miaaw.Domain.BasicBar;
import com.app.miaaw.Domain.TextToSpeech;
import com.app.miaaw.repos.TextToSpeechRepository;
import com.app.miaaw.requests.UpdateCodeRequest;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

/**
* Generated by Spring Data Generator on 23/04/2019
*/
@Component
@RestController
@RequestMapping("/tts")
public class TextToSpeechManager {

	private TextToSpeechRepository textToSpeechRepository;

	@Autowired
	public TextToSpeechManager(TextToSpeechRepository textToSpeechRepository) {
		this.textToSpeechRepository = textToSpeechRepository;
	}
	
	@GetMapping()
	public @ResponseBody String getTtsTemplate() {
		long id = 2;
		return textToSpeechRepository.findById(id).get().getCode();
	}
	
	@PostMapping()
	public void updateTtsCode(@RequestBody UpdateCodeRequest request) {
		long id = 2;
		TextToSpeech tts = textToSpeechRepository.findById(id).get();
		tts.setCode(request.getCode());
		textToSpeechRepository.save(tts);
	}
}
