package com.app.miaaw.managers;

import com.app.miaaw.Domain.TextToSpeech;
import com.app.miaaw.repos.TextToSpeechRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 23/04/2019
*/
@Component
public class TextToSpeechManager {

	private TextToSpeechRepository textToSpeechRepository;

	@Autowired
	public TextToSpeechManager(TextToSpeechRepository textToSpeechRepository) {
		this.textToSpeechRepository = textToSpeechRepository;
	}

}
