package com.app.miaaw.managers;

import com.app.miaaw.Domain.VideoOpties;
import com.app.miaaw.repos.VideoOptiesRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

/**
* Generated by Spring Data Generator on 30/04/2019
*/
@Component
public class VideoOptiesManager {

	private VideoOptiesRepository videoOptiesRepository;

	@Autowired
	public VideoOptiesManager(VideoOptiesRepository videoOptiesRepository) {
		this.videoOptiesRepository = videoOptiesRepository;
	}

}
